### ISSUE TITLE
Korjausehdotus Rubyn asennusohjeisiin Macille

### ISSUE THREAD

**Issue by areee** [mluukkai/WebPalvelinohjelmointi2016#1]
Moi!
Asensin Rubyn asennusohjeiden mukaisesti koneelleni, mutta sain komennolla `which ruby` seuraavan polun:
`/usr/bin/ruby`

Googlettelemalla löysin tällaisen [ohjeen](http://stackoverflow.com/a/12150580), jonka mukaan rivit

```
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)
```

kannattaa lisätä ~/.bash_profile -tiedostoon, ei siis ilmeisesti .bashrc -tiedostoon, kuten ohjeissanne lukee. Tuonne .bash_profile-tiedostoon laittamalla ainakin itselläni `which ruby` -komento tuottaa polun
`/Users/kayttajatunnus/.rbenv/shims/ruby`

PS. OS X-koneeni on versiota 10.11.2

**Comment by mluukkai** [comment]
uudemmissa ohjeissa tosiaan on noin, mun vanhassa macissa .bashrc oli oikea paikka. korjaan
