### ISSUE TITLE
Linkki ei toimi

### ISSUE THREAD

**Issue by lakaniemi** [mluukkai/WebPalvelinohjelmointi2016#11]
http://blog.dcxn.com/2011/09/30/the-simplest-possible-authentication-in-rails-http-auth-basic/ <-- tää linkki viikko2 materiaalin lähes lopussa antaa erroria, onko osoite varmasti oikea?

**Comment by mluukkai** [comment]
blogi näemmä hävinnyt. korvattu web archivessa olevalla versiolla
