### ISSUE TITLE
Väärä linkki?

### ISSUE THREAD

**Issue by Rochet2** [mluukkai/WebPalvelinohjelmointi2016#4]
Sivun https://github.com/mluukkai/WebPalvelinohjelmointi2016/wiki#materiaali-ja-laskarit
Materiaali ja laskarit kohdan alla viikko 1 linkki vie samalle sivulle (päivittää vain sivun)

Luullakseni sen tulisi viedä sivulle https://github.com/mluukkai/WebPalvelinohjelmointi2016/blob/master/web/viikko1.md

**Comment by mluukkai** [comment]
korjattu
